### ISSUE TITLE
When PUT'ing to a property, "MarketingDescription" is not updated

### ISSUE THREAD

**Issue by rg-jinwood** [letmeproperty/Properties#10]
{
  "PropertyReference": "",
  "PropertyUrl": "",
  "PropertyType": "Flat",
  "PropertyStatus": "Available",
  "AddressLine1": "Flat X",
  "AddressLine2": "Shore Road",
  "AddressLine3": "",
  "AddressLine4": "Southampton",
  "Postcode": "SO11 1UD",
  "County": "Hampshire",
  "PropertyDescription": "This truly STUNNING property is a real find! Situated in quiet suburb just off the Avenue, with M27 just 3 minute drive and Southampton City Centre only approximately 1 mile away. Perfect location for commuters or those looking for a bit of tranquility close to the town centre. The best of both worlds! The apartment further benefits from: - A recently fitted luxury kitchen with fully integrated appliances - a fridge/freezer/washing machine/dishwasher/oven & 5 point hob. Also features contemporary black gloss units and breakfast bar. - Both bedrooms are good size doubles and feature built in wardrobes. - New bathroom with jacuzzi bath and shower. - Spacious lounge/reception area leading to a separate dining area. - Offroad parking - Lovely private garden - Available now!",
  "FriendlyDescription": "Southampton Sure road 2 bed",
  "MarketingDescription": "This truly STUNNING property is a real find!  Perfect location for commuters or those looking for a bit of tranquility close to the town centre.",
  "StartDate": "2015-10-15T23:00:00",
  "EndDate": "2015-10-15T23:00:00",
  "MonthlyCost": 1100,
  "MonthlyPrice": 1350
}

Request URL

https://letme-properties.azurewebsites.net:443/api/properties?propertyReference=P-OTEDIx91G9

Response Body

no content

Response Code

200

Response Headers

{
  "cache-control": "no-cache",
  "pragma": "no-cache",
  "content-length": "0",
  "expires": "-1",
  "server": "Microsoft-IIS/8.0",
  "x-aspnet-version": "4.0.30319",
  "x-powered-by": "ASP.NET",
  "date": "Wed, 21 Oct 2015 10:30:47 GMT",
  "content-type": null
}

**Comment by rg-kristianwilson** [comment]
Marketing description has been removed and the description update issue fixed in 61f7ca7
