### ISSUE TITLE
Matched properties do not respect requirements for price

### ISSUE THREAD

**Issue by rg-jonathantansey** [letmeproperty/Properties#18]

**Comment by rg-kristianwilson** [comment]
Unable to reproduce, the call through swagger returns no results which tallies with what the query is returning from the database. I don't know where these matches are coming from but its not the service.

**Comment by rg-kristianwilson** [comment]
It appears there is  mismatch between the requirement names from applications and the search parameters causing the issue. Going to rename the search parameters to match.
